Solution Week 5 Section 2
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-rivki770 pull request #2
Opened 2022-03-15 22:39 UTC by rivki770

2022-03-20 09:33 UTC, itayday commented on cup_of_join.py
> +def join(*list_param, sep="-"):
1. Please add documantation.
2. Is there a way to simplify the function? (for example, by using list comprehension?)

2022-03-20 09:38 UTC, itayday commented on cut_a_cake.py
> +def get_recipe_price(prices, optionals=[], **ingredients):
Please add documantation to the function

2022-03-20 09:39 UTC, itayday commented on cut_a_cake.py
> +    for i in ingredients:
Try using a different name instead of "i" that will be more intuitive.
Same for "cost".

2022-03-25 21:14 UTC, talbarfm requested changes

2022-03-25 21:14 UTC, talbarfm commented on cup_of_join.py
> +    list_new = []
list_new is a bad variable name

2022-03-25 21:14 UTC, talbarfm commented on cup_of_join.py
> +        return None
Why return None and not an empty list, or throw an exception ?

2022-03-25 21:14 UTC, talbarfm commented on cup_of_join.py
> +    main()
Add a newline at eof

2022-03-25 21:14 UTC, talbarfm commented on cup_of_join.py
> +    for param in list_param:
Try to use list comprehension with multiple iterators instead of this for loop

2022-03-25 21:14 UTC, talbarfm commented on cut_a_cake.py
> +    main()
Add a newlist in end of file

2022-03-25 21:14 UTC, talbarfm commented on cut_a_cake.py
> +    print(get_recipe_price({'chocolate': 18, 'milk': 8}, chocolate=200, milk=100))
Use " for strings unless the string contains "

2022-03-25 21:14 UTC, talbarfm commented on cut_a_cake.py
> +    for i in ingredients:
You can use reduce to do this

2022-03-27 18:58 UTC, closed without merging