Week5part3
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-rivki770 pull request #3
Opened 2022-03-15 22:39 UTC by rivki770

2022-03-20 09:51 UTC, itayday commented on lachsheshanit.py
> +def main():
Please make separation between main and functions - you should write it in functions and call them in main.
Remember to add documantation to the functions you are about to write.

2022-03-26 12:11 UTC, talbarfm requested changes

2022-03-26 12:11 UTC, talbarfm commented on lachsheshanit.py
> +        with open("logo.jpg", "rb") as f:
Receive the file as a parameter , not as a const

2022-03-26 12:11 UTC, talbarfm commented on lachsheshanit.py
> +        with open("logo.jpg", "rb") as f:
f is a bad variable name

2022-03-26 12:11 UTC, talbarfm commented on lachsheshanit.py
> +            while byte:
Try to use regex instead of reading byte by byte

2022-03-26 12:11 UTC, talbarfm commented on lachsheshanit.py
> +    main()
Add a newline at the end

2022-03-26 12:11 UTC, talbarfm commented on lachsheshanit.py
> +        print('Error While Opening the file!')
Why Does Each Word Start With A Capital Letter?

2022-03-27 19:41 UTC, rivki770 commented on lachsheshanit.py
> +        print('Error While Opening the file!')
"המסרים הם מחרוזות באורך 5 אותיות לפחות, כתובים ב**אותיות אנגליות קטנות בלבד** ומסתיימים בסימן קריאה"

2022-03-27 19:59 UTC, closed without merging