Week5part4
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-rivki770 pull request #5
Opened 2022-03-16 11:04 UTC by rivki770

2022-03-20 09:55 UTC, itayday commented on harry_is_rational.py
> +def rename_files(path):
Please add documantation to the function.

2022-03-24 08:15 UTC, talbarfm requested changes

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +    list_of_file = os.listdir(path)
llist_of_files*

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +    list_of_file = os.listdir(path)
does listdir return only files? cant it return something else as well?

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +    for entry in list_of_file:
nice variable name :)

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +        codecs.register_error("strict", codecs.ignore_errors)
While the builtin [open()](https://docs.python.org/3/library/functions.html#open) and the associated [io](https://docs.python.org/3/library/io.html#module-io) module are the recommended approach for working with encoded text files, this module provides additional utility functions and classes that allow the use of a wider range of codecs when working with binary files:
from here - https://docs.python.org/3/library/codecs.html

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +        codecs.register_error("strict", codecs.ignore_errors)
why did you use codecs?

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +        f = codecs.open(full_path, 'r').read()
use full variable names - not a single character variable names

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +        title = title.split("Chapter ")  #we get title[o] = before chapter, title[1] = after chapter
Add spaces after # , add these comments on a separate line above this code

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +list_file = rename_files("C:\\rivki\\studies\\YearD\\SemesterB\\Excellent\\Python\\HW_1\\Git\\yam-mesika-weeks-5-6-rivki770\\potter")
Add a newline at the end of the file

2022-03-24 08:15 UTC, talbarfm commented on harry_is_rational.py
> +list_file = rename_files("C:\\rivki\\studies\\YearD\\SemesterB\\Excellent\\Python\\HW_1\\Git\\yam-mesika-weeks-5-6-rivki770\\potter")
https://www.freecodecamp.org/news/if-name-main-python-example/

2022-03-24 08:15 UTC, talbarfm commented on tools.py
> +    print(arr)
So much dup code
So much dup code
So much dup code
So much dup code
maybe export it to a function and call it a few times? :)

2022-03-24 08:15 UTC, talbarfm commented on tools.py
> +    arr = []
https://www.w3schools.com/python/python_arrays.asp
arrays are not supported in python, lists are :)

2022-03-24 08:15 UTC, talbarfm commented on tools.py
> +    main()
Add a newline at eof

2022-03-27 20:28 UTC, closed without merging